Patient.delete_all
Medicine.delete_all
Nurse.delete_all
Review.delete_all

Nurse.create([{name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name}])

Patient.create([{name: Faker::Name.name,  nurse_id: 1},
  {name: Faker::Name.name,  nurse_id: 2},
  {name: Faker::Name.name,  nurse_id: 3},
  {name: Faker::Name.name,  nurse_id: 4},
  {name: Faker::Name.name,  nurse_id: 5},
  {name: Faker::Name.name,  nurse_id: 6},
  {name: Faker::Name.name,  nurse_id: 7},
  {name: Faker::Name.name,  nurse_id: 8},
  {name: Faker::Name.name,  nurse_id: 9},
  {name: Faker::Name.name,  nurse_id: 10},
  {name: Faker::Name.name,  nurse_id: 11},
  {name: Faker::Name.name,  nurse_id: 12},
  {name: Faker::Name.name,  nurse_id: 13},
  {name: Faker::Name.name,  nurse_id: 14},
  {name: Faker::Name.name,  nurse_id: 15},
  {name: Faker::Name.name,  nurse_id: 16},
  {name: Faker::Name.name,  nurse_id: 17},
  {name: Faker::Name.name,  nurse_id: 16},
  {name: Faker::Name.name,  nurse_id: 15},
  {name: Faker::Name.name,  nurse_id: 14},
  {name: Faker::Name.name,  nurse_id: 13},
  {name: Faker::Name.name,  nurse_id: 12},
  {name: Faker::Name.name,  nurse_id: 11},
  {name: Faker::Name.name,  nurse_id: 10},
  {name: Faker::Name.name,  nurse_id: 9},
  {name: Faker::Name.name,  nurse_id: 8},
  {name: Faker::Name.name,  nurse_id: 7},
  {name: Faker::Name.name,  nurse_id: 6},
  {name: Faker::Name.name,  nurse_id: 5},
  {name: Faker::Name.name,  nurse_id: 4}
  ])

Nurse.create([{name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name}])

Review.create([{review_message: "It took me 4 weeks to adjust to the first phase of taking the medicine.",medicine_id:1, patient_id:1},
  {review_message: "I was unable to sleep since I started the medication.",medicine_id:2, patient_id:2},
  {review_message: "It makes me sweaty!", medicine_id:3, patient_id:3},
  {review_message: "I need to stop and go back to natural remedy.", medicine_id:4, patient_id:4},
  {review_message: "The medication is excellent and perfect for me.", medicine_id:5, patient_id:5},
  {review_message: "I think the dosage needs to be reduced.", medicine_id:6, patient_id:6},
  {review_message: "It makes me vomit!", medicine_id:7, patient_id:7},
  {review_message: "I always need fresh air anytime I take my medication.", medicine_id:8, patient_id:8},
  {review_message: "Excellent medication.", medicine_id:9, patient_id:9},
  {review_message: "I dont know if it is medication or my daily excercise", medicine_id:10, patient_id:10},
  {review_message: "Love it, it makes me feel energised", medicine_id:11, patient_id:11},
  {review_message: "Moving my daily food intake is important.", medicine_id:12, patient_id:12},
  {review_message: "I am going to move to another study.", medicine_id:13, patient_id:13},
  {review_message: "I am happy with the medicine and all the medical staffs.", medicine_id:14, patient_id:14},
  {review_message: "Excellent medicine", medicine_id:15, patient_id:15},
  {review_message: "I am getting better by the week", medicine_id:16, patient_id:16},
  {review_message: "Medication is too strong for me.", medicine_id:17, patient_id:17},
  {review_message: "The prescription makes me hungry.", medicine_id:18, patient_id:18}
  ])

  Medicine.create([{name: "Apixibucil", patient_id: 1, review_id: 17, nurse_id: 2},
  {name: "Adriacilin", patient_id: 1, review_id: 17, nurse_id: 12},
  {name: "Tiaferol", patient_id: 4, review_id: 2, nurse_id: 17},
  {name: "Afalinum", patient_id: 6, review_id: 7, nurse_id: 10},
  {name: "Pulmocilin", patient_id: 9, review_id: 9, nurse_id: 9},
  {name: "Afalinum", patient_id: 22, review_id: 13, nurse_id: 1},
  {name: "Acamkyn Thioderall", patient_id: 14, review_id: 1, nurse_id: 15},
  {name: "Arapan Empifenide", patient_id: 6, review_id: 18, nurse_id: 16},
  {name: "Dactinine Macrotaine", patient_id: 27, review_id: 4, nurse_id: 5},
  {name: "Alimcerol Epinethasone", patient_id: 1, review_id: 8, nurse_id: 7},
  {name: "Afalinum", patient_id: 25, review_id: 15, nurse_id: 11},
  {name: "Butabital", patient_id: 11, review_id: 6, nurse_id: 12},
  {name: "Altozyme", patient_id: 19, review_id: 8, nurse_id: 16},
  {name: "Hemadox", patient_id: 12, review_id: 12, nurse_id: 3},
  {name: "Altozyme", patient_id: 10, review_id: 17, nurse_id: 8},
  {name: "Eprothasol", patient_id: 4, review_id: 5, nurse_id: 9},
  {name: "Altozyme", patient_id: 8, review_id: 4, nurse_id: 13},
  {name: "Alfevelam Aprenone", patient_id: 30, review_id: 18, nurse_id: 9},
  {name: "Tiaferol", patient_id: 7, review_id: 6, nurse_id: 15},
  {name: "Tacropine Alogsonide", patient_id: 9, review_id: 3, nurse_id: 2},
  {name: "Tiaferol", patient_id: 16, review_id: 11, nurse_id: 17}
  ])
