Patient.delete_all
Medicine.delete_all
Nurse.delete_all
Review.delete_all

Patient.create({name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name}])

Nurse.create({name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name},
  {name: Faker::Name.name}])

Review.create([{review_message: "Lorem ipsum dolor sit amet."},
  {review_message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
  {review_message: "Proin ac lacus a eros accumsan interdum ac quis felis."},
  {review_message: "Cras nec augue non leo viverra malesuada."},
  {review_message: "Phasellus a odio id augue iaculis porttitor non sit."},
  {review_message: "Morbi quis ipsum sit amet sapien accumsan pellentesque."},
  {review_message: "Donec eget arcu ullamcorper, feugiat nisl a, varius diam."},
  {review_message: "Suspendisse condimentum libero quis turpis suscipit con."},
  {review_message: "Curabitur porttitor enim vel lectus sollicitudin, qui."},
  {review_message: "Etiam vel ex sit amet mi rhoncus consectetur vestibulum."},
  {review_message: "Nulla a libero ac ligula laoreet consectetur non sit amet."},
  {review_message: "Phasellus at magna at orci ornare dictum vel vitae sem."},
  {review_message: "Quisque eget erat ut mi elementum mattis ut ut felis."},
  {review_message: "Curabitur ullamcorper massa id ex ultrices blandit."},
  {review_message: "Maecenas vel dui pulvinar, efficitur elit non, placerat leo."},
  {review_message: "Vestibulum id massa pellentesque, commodo urna vel, molesti."},
  {review_message: "Phasellus a odio id augue iaculis porttitor non sit amet risus."},
  {review_message: "Vestibulum id massa pellentesque, commodo urna vel, molestie risus."}
  ])

  Medicine.Create([{name: "Apixibucil"},
  {name: "Adriacilin"},
  {name: "Somasulin"},
  {name: "Alcaftonin"},
  {name: "Pulmocilin"},
  {name: "Afalinum"},
  {name: "Acamkyn Thioderall"},
  {name: "Arapan Empifenide"},
  {name: "Dactinine Macrotaine"},
  {name: "Alimcerol Epinethasone"},
  {name: "Alglucoroban"},
  {name: "Butabital"},
  {name: "Altozyme"},
  {name: "Hemadox"},
  {name: "Naveltone"},
  {name: "Eprothasol"},
  {name: "Unidizem Ambegestrel"},
  {name: "Alfevelam Aprenone"},
  {name: "Acetylnovate Novalapril"},
  {name: "Tacropine Alogsonide"},
  {name: "Tiaferol"}
  ])
